### ISSUE TITLE
Check Cauchy calculation

### ISSUE THREAD

**Issue by andyfaff** [refnx/refellips#22]
Is the real part of the Cauchy calculation being done correctly: https://github.com/refnx/refellips/blob/master/refellips/structureSE.py#L166

Should it read:
```
self.C.value * 1000**4) / (wavelength**4)
```
instead of:
```
self.C.value**1000**4) / (wavelength**4)
```

**Comment by haydenrob** [comment]
You are correct, should be * not **. It's just taking into account that we're swapping between different units. Will you fix this?

**Comment by andyfaff** [comment]
I'll fix
